name: Test Run

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  checks: write
  pull-requests: write

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Git clone
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependences
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check Chrome version
        run: |
          google-chrome --version
        env:
          CICD_RUN: "yes"

      - name: Test with pytest and generate junit xml report
        run : |
          pytest uidemotest/test --junitxml report.xml

      - name: Create test summary
        uses: test-summary/action@v1.0
        with:
          paths: report.xml
        if: always()

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v1.36
        if: always()
        with:
          files: "report.xml"
